export const mockProducts = [
  {
    id: "prod-001",
    name: "Bespoke Oud Reserve",
    slug: "bespoke-oud-reserve",
    category: "OUD BLENDS",
    price: 145,
    stock_status: "in_stock",
    stock_quantity: 15,
    scent_family: "Oud Extrait",
    key_notes: ["Saffron", "Smoked Oud", "Amber"],
    description: "A majestic aura of red saffron and smoked agarwood, lingering like a warm memory long after you've gone—an unforgettable essence of you.",
    scent_mixes: "Pure Cambodian Oud oil (35%), Saffron concentrate, Ambergris resin, Madagascar Vanilla absolute.",
    images: ["https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&q=80&w=600"],
    sillage: 90,
    longevity: 95,
    gender: 50,
    batch_details: "Batch #026 — Freshly hand-poured in Dubai",
    scarcity_note: "Limited Release — Only 100 bottles crafted annually"
  },
  {
    id: "prod-002",
    name: "Amber Royale",
    slug: "amber-royale",
    category: "SIGNATURE EXTRAITS",
    price: 195,
    stock_status: "in_stock",
    stock_quantity: 8,
    scent_family: "Warm Amber",
    key_notes: ["Labdanum", "Vanilla", "Benzoin"],
    description: "An opulent, resinous warmth that wraps around you like a royal velvet cloak. Deeply comforting yet unmistakably sovereign.",
    scent_mixes: "Natural Amber resin (28%), Turkish Rose extract, Somalian Myrrh, Vanilla bean infusion.",
    images: ["https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&q=80&w=600"],
    sillage: 75,
    longevity: 90,
    gender: 45,
    batch_details: "Batch #012 — Aged in oak barrels",
    scarcity_note: "VIP Exclusivity — Reserved for private collection members"
  },
  {
    id: "prod-003",
    name: "Musk Imperial",
    slug: "musk-imperial",
    category: "MUSK BLENDS",
    price: 135,
    stock_status: "in_stock",
    stock_quantity: 20,
    scent_family: "Musk",
    key_notes: ["White Musk", "Jasmine", "Sandalwood"],
    description: "A clean, powdery whisper that rests closely on the skin. A delicate balance of fresh white blossoms and deep warm sandalwood.",
    scent_mixes: "Premium White Musk, Egyptian Jasmine oil, Mysore Sandalwood extract, hints of soft Iris.",
    images: ["https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&q=80&w=600"],
    sillage: 40,
    longevity: 70,
    gender: 30,
    batch_details: "Batch #034 — Softest floral curation",
    scarcity_note: "Classic Selection — Blended for intimate elegance"
  },
  {
    id: "prod-004",
    name: "Dubai Meydan",
    slug: "dubai-meydan",
    category: "SIGNATURE EXTRAITS",
    price: 245,
    stock_status: "in_stock",
    stock_quantity: 12,
    scent_family: "Leather Woody",
    key_notes: ["Leather", "Saffron", "Patchouli"],
    description: "Capturing the spirit of the prestigious horse racing tracks, embodying the ultimate scent of luxury leather, rich spices, and green woods.",
    scent_mixes: "Tuscan Leather chord (30%), Persian Saffron, Indonesian Patchouli, Cedarwood shavings.",
    images: ["https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&q=80&w=600"],
    sillage: 95,
    longevity: 95,
    gender: 85,
    batch_details: "Batch #008 — Royal equestrian series",
    scarcity_note: "Prestigious Batch — Crafted using rare raw ingredients"
  },
  {
    id: "prod-005",
    name: "Saffron Sillage",
    slug: "saffron-sillage",
    category: "SIGNATURE EXTRAITS",
    price: 165,
    stock_status: "low_stock",
    stock_quantity: 3,
    scent_family: "Spicy Floral",
    key_notes: ["Saffron", "Taif Rose", "Cardamom"],
    description: "A brilliant projection of hand-harvested Taif roses balanced by the dry, vibrant spiciness of freshly crushed cardamom and saffron threads.",
    scent_mixes: "Taif Rose petals (40%), Iranian Saffron extract, Green Cardamom oil, Cedarwood base.",
    images: ["https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&q=80&w=600"],
    sillage: 80,
    longevity: 85,
    gender: 50,
    batch_details: "Batch #019 — Harvested at dawn",
    scarcity_note: "Limited Stock — Hand-selected Taif rose petals"
  },
  {
    id: "prod-006",
    name: "Sandalwood Extrait",
    slug: "sandalwood-extrait",
    category: "MUSK BLENDS",
    price: 175,
    stock_status: "in_stock",
    stock_quantity: 18,
    scent_family: "Woody Cream",
    key_notes: ["Mysore Sandalwood", "Cardamom", "Cedar"],
    description: "A creamy, smooth wood symphony that radiates soft golden warmth. Perfectly balanced with a pinch of dynamic green spices.",
    scent_mixes: "Pure Mysore Sandalwood (35%), Cardamom seeds, Virginian Cedarwood, Cashmeran blend.",
    images: ["https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&q=80&w=600"],
    sillage: 60,
    longevity: 80,
    gender: 60,
    batch_details: "Batch #022 — Smooth golden oil extraction",
    scarcity_note: "Bespoke blend — Limited to 150 bottles per season"
  },
  {
    id: "prod-007",
    name: "Vanilla Absolute",
    slug: "vanilla-absolute",
    category: "MUSK BLENDS",
    price: 155,
    stock_status: "in_stock",
    stock_quantity: 14,
    scent_family: "Gourmand Musk",
    key_notes: ["Vanilla Pods", "White Musk", "Caramel"],
    description: "An intoxicating, elevated sweetness. Deep, smokey vanilla beans refined with powdery clean musk and a whisper of warm caramel glaze.",
    scent_mixes: "Bourbon Vanilla pods, Tonka Bean extract, Soft White Musk, Salted Caramel.",
    images: ["https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&q=80&w=600"],
    sillage: 70,
    longevity: 85,
    gender: 35,
    batch_details: "Batch #027 — Concentrated bean extraction",
    scarcity_note: "Special reserve — Exquisite gourmand balance"
  },
  {
    id: "prod-008",
    name: "Rose Damascena",
    slug: "rose-damascena",
    category: "OUD BLENDS",
    price: 185,
    stock_status: "in_stock",
    stock_quantity: 7,
    scent_family: "Oud Floral",
    key_notes: ["Damask Rose", "Light Oud", "Patchouli"],
    description: "A gorgeous, velvet red rose floating on a soft bed of smokey light oud and earthy patchouli. A timeless romance captured in oil.",
    scent_mixes: "Damask Rose oil (30%), Indian Light Oud extract, Patchouli oil, Bergamot top notes.",
    images: ["https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&q=80&w=600"],
    sillage: 85,
    longevity: 90,
    gender: 45,
    batch_details: "Batch #004 — Floral infusion cycle",
    scarcity_note: "Delicate Selection — Handcrafted luxury blend"
  },
  {
    id: "prod-009",
    name: "Sovereign Saffron",
    slug: "sovereign-saffron",
    category: "SIGNATURE EXTRAITS",
    price: 210,
    stock_status: "in_stock",
    stock_quantity: 11,
    scent_family: "Warm Spicy",
    key_notes: ["Persian Saffron", "Black Pepper", "Amberwood"],
    description: "A commanding warm aura of premium hand-gathered Persian saffronThreads, balanced by dry black pepper oil and rich sensual amberwood resins.",
    scent_mixes: "Persian Saffron oil (25%), Black Pepper absolute, Amberwood extract, Guaiacwood oil.",
    images: ["https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&q=80&w=600"],
    sillage: 80,
    longevity: 90,
    gender: 70,
    batch_details: "Batch #009 — Hand-selected Persian spice",
    scarcity_note: "Limited Supply — Harvested once per autumn season"
  },
  {
    id: "prod-010",
    name: "Oud Céleste",
    slug: "oud-celeste",
    category: "OUD BLENDS",
    price: 260,
    stock_status: "in_stock",
    stock_quantity: 5,
    scent_family: "Aromatic Oud",
    key_notes: ["White Lavender", "White Oud", "Olibanum"],
    description: "An ethereal and airy oud blend, pairing fresh crystalline mountain lavender with precious white agarwood oil and sacred incense resins.",
    scent_mixes: "Precious White Oud oil (20%), Blue French Lavender extract, Somalian Olibanum, clean Ambergris.",
    images: ["https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&q=80&w=600"],
    sillage: 85,
    longevity: 95,
    gender: 50,
    batch_details: "Batch #002 — Ethereal wood curation",
    scarcity_note: "Royal Reserve — Sourced from highly secluded forest agarwood"
  },
  {
    id: "prod-011",
    name: "Gilded Neroli",
    slug: "gilded-neroli",
    category: "SIGNATURE EXTRAITS",
    price: 140,
    stock_status: "in_stock",
    stock_quantity: 19,
    scent_family: "Citrus Nectar",
    key_notes: ["Orange Blossom", "Raw Honey", "Ambergris"],
    description: "A luminous honeyed citrus dream. Pristine white orange blossoms glowing under sun-drenched amber honey nectar and sea-salted ambergris.",
    scent_mixes: "Tunisian Neroli absolute (30%), Raw Clover Honey, Sea-salt Ambergris, Bergamot zest.",
    images: ["https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&q=80&w=600"],
    sillage: 70,
    longevity: 80,
    gender: 40,
    batch_details: "Batch #014 — Pressed under midday sun",
    scarcity_note: "Fresh Release — Perfect signature spring radiance"
  },
  {
    id: "prod-012",
    name: "Patchouli Noir",
    slug: "patchouli-noir",
    category: "SIGNATURE EXTRAITS",
    price: 160,
    stock_status: "in_stock",
    stock_quantity: 10,
    scent_family: "Earthy Woody",
    key_notes: ["Indonesian Patchouli", "Dark Cocoa", "Warm Smoke"],
    description: "A mysterious, deep dark wood symphony. Rich, age-mellowed Indonesian patchouli leaves steeped with warm smoke, dark cocoa beans, and dry leather.",
    scent_mixes: "Aged Indonesian Patchouli (32%), Roasted Cocoa pod extract, Vetiver root, Birch Tar smoke.",
    images: ["https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&q=80&w=600"],
    sillage: 80,
    longevity: 90,
    gender: 65,
    batch_details: "Batch #007 — Double-distilled dark wood",
    scarcity_note: "Artisanal Blend — Steeped for 180 days before hand-pour"
  },
  {
    id: "prod-013",
    name: "Imperial Iris",
    slug: "imperial-iris",
    category: "MUSK BLENDS",
    price: 220,
    stock_status: "in_stock",
    stock_quantity: 6,
    scent_family: "Powdery Floral",
    key_notes: ["Tuscan Iris", "Powdery Musk", "Soft Violet"],
    description: "An elegant, velvet powder cloud. The extremely rare concrete of Tuscan Iris root, softened by fluffy white musk and delicate morning violets.",
    scent_mixes: "Rare Tuscan Iris Pallida resin (15%), Powdery Skin Musk, Violet concrete, Sandalwood base.",
    images: ["https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&q=80&w=600"],
    sillage: 50,
    longevity: 85,
    gender: 25,
    batch_details: "Batch #003 — Aged iris root concrete extraction",
    scarcity_note: "Ultra Exclusive — Iris root aged 3 years before oil pressing"
  },
  {
    id: "prod-014",
    name: "Bergamot Sovereign",
    slug: "bergamot-sovereign",
    category: "SIGNATURE EXTRAITS",
    price: 130,
    stock_status: "in_stock",
    stock_quantity: 25,
    scent_family: "Fresh Citrus",
    key_notes: ["Calabrian Bergamot", "Haitian Vetiver", "Oakmoss"],
    description: "A bright, clean sovereign burst. Sparkling zesty bergamot orange from Calabria, balanced by dry, smoky vetiver roots and wet earthy oakmoss.",
    scent_mixes: "Calabrian Bergamot cold-press (30%), Haitian Vetiver oil, French Oakmoss absolute, Cedar.",
    images: ["https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&q=80&w=600"],
    sillage: 65,
    longevity: 75,
    gender: 60,
    batch_details: "Batch #031 — Cold-pressed citrus harvest",
    scarcity_note: "Fresh Collection — A vibrant day-long projection of freshness"
  },
  {
    id: "prod-015",
    name: "Myrrh Nomade",
    slug: "myrrh-nomade",
    category: "SIGNATURE EXTRAITS",
    price: 180,
    stock_status: "in_stock",
    stock_quantity: 9,
    scent_family: "Resinous Warm",
    key_notes: ["Somalian Myrrh", "Warm Cedar", "Vanilla Pod"],
    description: "A rich, balsamic desert journey. Sacred Somalian myrrh tears melting over a crackling dry cedar wood fire and sweet smoky vanilla pod infusions.",
    scent_mixes: "Natural Somalian Myrrh (25%), Virginian Cedarwood oil, Vanilla bean absolute, Frankincense.",
    images: ["https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&q=80&w=600"],
    sillage: 75,
    longevity: 90,
    gender: 55,
    batch_details: "Batch #011 — Resinous balsamic maceration",
    scarcity_note: "Rare Release — Formulated using sacred desert resins"
  },
  {
    id: "prod-016",
    name: "Violet Silk",
    slug: "violet-silk",
    category: "MUSK BLENDS",
    price: 150,
    stock_status: "in_stock",
    stock_quantity: 15,
    scent_family: "Soft Powdery",
    key_notes: ["Parma Violet", "White Musk", "Heliotrope"],
    description: "A clean, powdery floral veil. The whispering sweetness of classic violet petals wrapped in fluffy white musk and almond-like heliotrope blossoms.",
    scent_mixes: "Parma Violet extract, Fluffy Skin Musk, Heliotrope flowers, soft Amber base.",
    images: ["https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&q=80&w=600"],
    sillage: 45,
    longevity: 80,
    gender: 20,
    batch_details: "Batch #015 — Soft spring floral blend",
    scarcity_note: "Delicate Edition — Blended for an intimate, clean powder aura"
  },
  {
    id: "prod-017",
    name: "Jasmine Velvet",
    slug: "jasmine-velvet",
    category: "MUSK BLENDS",
    price: 170,
    stock_status: "in_stock",
    stock_quantity: 12,
    scent_family: "Rich Floral",
    key_notes: ["Egyptian Jasmine", "Creamy Sandalwood", "Musk"],
    description: "An intoxicating night-blooming Egyptian jasmine floral heart, balanced beautifully on a base of warm, creamy Indian sandalwood and clean musk oils.",
    scent_mixes: "Egyptian Jasmine Grandiflorum (30%), Mysore Sandalwood extract, White Musk, Ylang-Ylang.",
    images: ["https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&q=80&w=600"],
    sillage: 75,
    longevity: 85,
    gender: 25,
    batch_details: "Batch #018 — Petals gathered at midnight",
    scarcity_note: "Special Selection — Intoxicating sweet floral projection"
  },
  {
    id: "prod-018",
    name: "Cedarwood Smoke",
    slug: "cedarwood-smoke",
    category: "SIGNATURE EXTRAITS",
    price: 165,
    stock_status: "in_stock",
    stock_quantity: 14,
    scent_family: "Smoky Woody",
    key_notes: ["Virginia Cedar", "Guaiacwood", "Green Cardamom"],
    description: "A dry, smoky mountain log cabin aroma. Premium virginian cedar wood logs burning next to aromatic green cardamom spices and smoky guaiacwood resin.",
    scent_mixes: "Virginia Cedarwood oil (35%), Guaiacwood absolute, Green Cardamom pods, Smoky Vetiver.",
    images: ["https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&q=80&w=600"],
    sillage: 80,
    longevity: 90,
    gender: 80,
    batch_details: "Batch #021 — Distilled smoky wood logs",
    scarcity_note: "Earthy Selection — For those who command a rich woody sillage"
  },
  {
    id: "prod-019",
    name: "Incense Sovereign",
    slug: "incense-sovereign",
    category: "OUD BLENDS",
    price: 230,
    stock_status: "in_stock",
    stock_quantity: 8,
    scent_family: "Sacred Warm",
    key_notes: ["Sacred Olibanum", "Warm Amber", "Smoked Oud"],
    description: "A sacred temple aura of sweet frankincense olibanum smoke, melting over a base of warm honeyed amber resins and prestigious smoked agarwood.",
    scent_mixes: "Sacred Somalian Olibanum (28%), Rich Baltic Amber, Smoked Cambodian Oud, Cedar.",
    images: ["https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&q=80&w=600"],
    sillage: 90,
    longevity: 95,
    gender: 60,
    batch_details: "Batch #005 — Aged temple incense maceration",
    scarcity_note: "Sacred Series — Reserved for ultimate connoisseurs of smoke"
  },
  {
    id: "prod-020",
    name: "Spiced Ambergris",
    slug: "spiced-ambergris",
    category: "SIGNATURE EXTRAITS",
    price: 250,
    stock_status: "low_stock",
    stock_quantity: 2,
    scent_family: "Marine Balsamic",
    key_notes: ["Ambergris", "Pink Pepper", "Bourbon Vanilla"],
    description: "A breathtaking marine warmth. Natural sea-aged salty ambergris threads spiced with sparkling dry pink peppercorns and sweet bourbon vanilla pod pods.",
    scent_mixes: "Natural Marine Ambergris (20%), Pink Peppercorns, Bourbon Vanilla absolute, Labdanum.",
    images: ["https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&q=80&w=600"],
    sillage: 85,
    longevity: 95,
    gender: 50,
    batch_details: "Batch #001 — Ocean-harvested raw ambergris",
    scarcity_note: "Ultra Rare Release — Only 20 bottles created due to raw ambergris rarity"
  }
];

export const mockDiscoverySet = {
  id: "prod-disc",
  name: "Elixyr Discovery Set",
  description: "Test the complete Elixyr portfolio. A luxurious gold-embossed presentation box holding 2ml spray vials of our Oud, Musk, Amber, Dubai Meydan, and Signature blends.",
  price: 95,
  stock_status: "in_stock",
  images: [
    "https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&q=80&w=600"
  ],
  vials: [
    { name: "OUD", notes: "Saffron, Smoked Oud, Amber" },
    { name: "AMBER", notes: "Labdanum, Vanilla, Myrrh" },
    { name: "MUSK", notes: "White Musk, Jasmine, Sandalwood" },
    { name: "VANILLA", notes: "Vanilla Pod, White Musk, Caramel" }
  ]
};

export const mockCuratedSets = [
  {
    id: "set-001",
    name: "The Sovereign Oud Set",
    slug: "the-sovereign-oud-set",
    scent_direction: "Rich, Deep Oud & Incense",
    best_for: "Royal evenings, formal Majlis gatherings, statement wear",
    best_suited_for: "Anyone who enjoys rich, smoky, and highly intense woody scents",
    scents_included: "Bespoke Oud Reserve (100ml), Oud Céleste (100ml), Incense Sovereign (100ml)",
    scents_list: [
      { name: "Bespoke Oud Reserve", description: "Saffron, Smoked Oud, Amber" },
      { name: "Oud Céleste", description: "White Lavender, White Oud, Olibanum" },
      { name: "Incense Sovereign", description: "Sacred Olibanum, Warm Amber, Smoked Oud" }
    ],
    description: "A commanding presence of aged Cambodi agarwood and holy frankincense smoke. A majestic trio engineered for maximum projection and unmatched longevity.",
    why_it_works_as_gift: "A prestigious gift of absolute luxury that honors the rich traditions of Middle Eastern perfumery.",
    price: 595,
    images: ["https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&q=80&w=600"],
    stock_status: "in_stock",
    stock_quantity: 12
  },
  {
    id: "set-002",
    name: "The Imperial Musk & Amber Set",
    slug: "the-imperial-musk-amber-set",
    scent_direction: "Soft Powdery Musk & Warm Amber",
    best_for: "Intimate gatherings, daily signature wear, comforting warmth",
    best_suited_for: "Anyone who enjoys soft, fresh, sweet, and amber scents",
    scents_included: "Musk Imperial (100ml), Amber Royale (100ml), Vanilla Absolute (100ml)",
    scents_list: [
      { name: "Musk Imperial", description: "White Musk, Jasmine, Sandalwood" },
      { name: "Amber Royale", description: "Labdanum, Vanilla, Benzoin" },
      { name: "Vanilla Absolute", description: "Vanilla Pods, White Musk, Caramel" }
    ],
    description: "A harmonious balance of clean skin musk, opulent amber resins, and smoky Madagascar vanilla. An intimate yet distinctly sovereign fragrance journey.",
    why_it_works_as_gift: "A warm and inviting olfactory embrace that feels incredibly personal, elegant, and comforting.",
    price: 425,
    images: ["https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&q=80&w=600"],
    stock_status: "in_stock",
    stock_quantity: 15
  },
  {
    id: "set-003",
    name: "The Sovereign Discovery Set",
    slug: "the-sovereign-discovery-set",
    scent_direction: "Full Olfactory House Introduction",
    best_for: "Daily exploration, finding your signature scent, luxury travel",
    best_suited_for: "Curious perfume lovers wishing to explore the complete range without confusion",
    scents_included: "5 x 2ml spray vials (Bespoke Oud, Amber Royale, Musk Imperial, Dubai Meydan, Saffron Sillage)",
    scents_list: [
      { name: "Bespoke Oud Reserve", description: "Saffron, Smoked Oud, Amber" },
      { name: "Amber Royale", description: "Labdanum, Vanilla, Benzoin" },
      { name: "Musk Imperial", description: "White Musk, Jasmine, Sandalwood" },
      { name: "Dubai Meydan", description: "Leather, Saffron, Patchouli" },
      { name: "Saffron Sillage", description: "Saffron, Taif Rose, Cardamom" }
    ],
    description: "The ultimate introduction to the house of ELIXYR. Test and layer five extraordinary extraits before selecting your full signature bottle.",
    why_it_works_as_gift: "The ultimate, elegant gift that lets them discover their own favorite scent journey.",
    price: 95,
    images: ["https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&q=80&w=600"],
    stock_status: "in_stock",
    stock_quantity: 45
  }
];

export const mockBlogs = [
  {
    id: "blog-001",
    title: "How to choose a lasting perfume in the UAE climate",
    slug: "how-to-choose-lasting-perfume-uae",
    category: "BUYING GUIDE",
    excerpt: "Heat, fabric, skin profiles, and timing all change how a fragrance wears through the day in warm regions.",
    content: "The extreme climate of the Arabian Gulf demands specific qualities in a perfume. High temperatures evaporate top notes at twice the speed of temperate regions, leaving the base and mid notes to carry the fragrance. When selecting a fragrance for the UAE heat, seek high-concentration 'Extraits de Parfum' rather than light Eaux de Toilette. Focus on heavy molecular base structures—such as oud, sandalwood, ambergris, and patchouli—which bind closely to the skin and project elegantly even in high humidity. Additionally, consider fabric profiles; natural linen and silk carry fragrance differently than warm wools. A sophisticated application involves a light spray on raw inner clothing seams, providing an continuous, elegant sillage throughout the daytime."
  },
  {
    id: "blog-002",
    title: "Oud, amber, musk, and vanilla with subtle balance",
    slug: "oud-amber-musk-vanilla-subtle-balance",
    category: "FRAGRANCE NOTES",
    excerpt: "Deep materials can feel polished when the blend has air, restraint, and balanced Taif floral curation.",
    content: "The heavyweights of oriental perfumery—Oud, Amber, Musk, and Vanilla—are often misunderstood as overwhelming. In high-end boutique blending, the secret lies in 'air' and restraint. By pairing powerful Cambodian Oud with breezy floral high-notes like Taif Rose or Sicilian Bergamot, a master blender creates space for the wood to breathe. This subtle counterweight results in an olfactory silhouette that is strong yet quiet. A premium fragrance should never arrive before you do, nor linger obtrusively after you leave. Instead, it should act as a subtle, elegant shadow that quietly defines your personal aura."
  },
  {
    id: "blog-003",
    title: "Perfume gifts for Eid, weddings, and formal UAE visits",
    slug: "perfume-gifts-eid-weddings-uae-visits",
    category: "GIFTING",
    excerpt: "Choose a scent that feels personal, elegant, and easy to wear after the initial celebratory occasion.",
    content: "Gifting perfume in the UAE is a gesture of deep respect, hospitality, and intimacy. For sacred occasions like Eid al-Fitr, weddings, or high-level Majlis meetings, gifting requires careful curation. The packaging must represent the caliber of the ingredients within. Seek gold-embossed boutique presentations or customizable Discovery sets. When choosing a scent profile, opt for warm, universally admired signature extracts like amber-rich florals or creamy sandallwoods. These carry a rich presence that respects local traditions while remaining versatile and elegant enough for daily wearing."
  },
  {
    id: "blog-004",
    title: "Where to apply perfume so it settles with the day",
    slug: "where-to-apply-perfume-settles-with-day",
    category: "RITUAL",
    excerpt: "Pulse points, premium inner fabric layers, and distance create a softer trail than spraying heavily.",
    content: "Applying a luxury perfume is a sensory ritual, not a rushed final step. The magic of premium oils is activated by warm blood circulation. Target key pulse points: the insides of the wrists, the crook of the elbow, behind the ears, and along the collarbones. However, avoid the common mistake of 'rubbing' wrists together—this friction breaks down the delicate top-note molecules, altering the blend's evolution. Instead, spray from a distance of 15cm and let the mist dry naturally. For a lasting, whispering trail, spray once into the air and step through the mist, letting it settle delicately onto your hair or jacket shoulders."
  }
];

export const ADMIN_HASH = "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918"; // SHA-256 hash of "admin"
export const MASTER_HASH = "c6f8643f9bcadbe33c4fefc062f5e9eb1702cdc3f0e024f93098eab685b742cb"; // SHA-256 of "elixyr2026"
export const DEMO_HASH = "5994471abb01112afcc18159f6cc74b4f511b99806da59b3caf5a9c173cacfc5"; // SHA-256 of "12345"
